### ISSUE TITLE
domain authentication?

### ISSUE THREAD

**Issue by Spambustas** [RowTeam/SharpExchangeKing#2]
Does this burp method support domain authentication?

**Comment by RcoIl** [comment]
Using a thread pool with a default maximum of 10, currently only EWS interface authentication is supported, which supports NLTM authentication. There are 5 modes for mixing account and password combinations:

Single account single password: Fill in the account and password separately in the UserName and PassWord fields.

Single account multiple passwords: Fill in the account in the UserName field and the local text path containing the passwords in the PassWord field.

Multiple accounts single password: Fill in the local text path containing the accounts in the UserName field and the password in the PassWord field.

Multiple accounts multiple passwords: Fill in the local text path containing the accounts in the UserName field and the local text path containing the passwords in the PassWord field.

Bulk verification of account passwords: Fill in the local text path containing the account passwords in the UserName field. The format must be "username:password".

PS: If the multiple passwords above are in NTLM format, select NTLM. Plain text and NTLM cannot be used simultaneously.


I haven't considered other situations for now because my local Exchange test environment allows logging in without a domain, only using an account and password.Therefore, I am not sure if it is possible or not.
